from enum import StrEnum


class SourceType(StrEnum):
    BRD_EXCEL = "BRD_EXCEL"
    BRD_DOCX = "BRD_DOCX"
    BRD_PDF = "BRD_PDF"
    JIRA_MARKDOWN = "JIRA_MARKDOWN"
    JIRA_EXPORT = "JIRA_EXPORT"
    FLOW_PDF = "FLOW_PDF"


class DataClassification(StrEnum):
    PUBLIC = "PUBLIC"
    INTERNAL = "INTERNAL"
    CONFIDENTIAL = "CONFIDENTIAL"
    RESTRICTED = "RESTRICTED"


class ProcessingStatus(StrEnum):
    QUEUED = "QUEUED"
    PROCESSING = "PROCESSING"
    COMPLETED = "COMPLETED"
    COMPLETED_WITH_WARNINGS = "COMPLETED_WITH_WARNINGS"
    FAILED = "FAILED"
    BLOCKED = "BLOCKED"
    REQUIRES_MANUAL_REVIEW = "REQUIRES_MANUAL_REVIEW"


class RunStatus(StrEnum):
    CREATED = "CREATED"
    PROCESSING = "PROCESSING"
    AWAITING_REVIEW = "AWAITING_REVIEW"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class TestType(StrEnum):
    POSITIVE = "POSITIVE"
    NEGATIVE = "NEGATIVE"
    BOUNDARY = "BOUNDARY"
    VALIDATION = "VALIDATION"
    EXCEPTION = "EXCEPTION"
    INTEGRATION = "INTEGRATION"
    END_TO_END = "END_TO_END"


class Priority(StrEnum):
    CRITICAL = "CRITICAL"
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"
    UNKNOWN = "UNKNOWN"


class ReviewStatus(StrEnum):
    DRAFT = "DRAFT"
    NEEDS_REVIEW = "NEEDS_REVIEW"
    NEEDS_CLARIFICATION = "NEEDS_CLARIFICATION"
    REJECTED = "REJECTED"
    APPROVED = "APPROVED"


class ValidationStatus(StrEnum):
    PASSED = "PASSED"
    WARNING = "WARNING"
    FAILED = "FAILED"
    BLOCKED = "BLOCKED"


class FindingSeverity(StrEnum):
    BLOCKING = "BLOCKING"
    WARNING = "WARNING"
    INFO = "INFO"


class ApplicabilityStatus(StrEnum):
    APPLICABLE = "APPLICABLE"
    EXCLUDED = "EXCLUDED"
    UNRESOLVED = "UNRESOLVED"


class PathType(StrEnum):
    MAIN = "MAIN"
    ALTERNATE = "ALTERNATE"
    EXCEPTION = "EXCEPTION"
    LOOP = "LOOP"


class LinkStatus(StrEnum):
    CONFIRMED = "CONFIRMED"
    CANDIDATE = "CANDIDATE"
    BROKEN = "BROKEN"
    EXCLUDED = "EXCLUDED"


class EntityType(StrEnum):
    REQUIREMENT = "REQUIREMENT"
    STORY = "STORY"
    CRITERION = "CRITERION"
    FLOW_PATH = "FLOW_PATH"
    TEST_CASE = "TEST_CASE"
    SOURCE = "SOURCE"


class ExportFormat(StrEnum):
    JSON = "JSON"
    CSV = "CSV"
    XLSX = "XLSX"


class AuditEventType(StrEnum):
    RUN_CREATED = "RUN_CREATED"
    SOURCE_REGISTERED = "SOURCE_REGISTERED"
    SOURCE_PARSED = "SOURCE_PARSED"
    EXTRACTION_COMPLETED = "EXTRACTION_COMPLETED"
    EXTRACTION_WARNING = "EXTRACTION_WARNING"
    NORMALIZATION_COMPLETED = "NORMALIZATION_COMPLETED"
    GAP_IDENTIFIED = "GAP_IDENTIFIED"
    GENERATION_REQUESTED = "GENERATION_REQUESTED"
    GENERATION_COMPLETED = "GENERATION_COMPLETED"
    GENERATION_FAILED = "GENERATION_FAILED"
    VALIDATION_COMPLETED = "VALIDATION_COMPLETED"
    CASE_EDITED = "CASE_EDITED"
    CASE_APPROVED = "CASE_APPROVED"
    CASE_REJECTED = "CASE_REJECTED"
    EXPORT_COMPLETED = "EXPORT_COMPLETED"
    ACCESS_DENIED = "ACCESS_DENIED"
    SECURITY_EVENT = "SECURITY_EVENT"
